language: go

go:
    - tip
    - 1.9
    - 1.8
    - 1.7

env:
    global:
        - GO15VENDOREXPERIMENT=1
        - DEP_VERSION="v0.3.2"

notifications:
    email: false

before_install:
    - curl -o /tmp/dep --location https://github.com/golang/dep/releases/download/${DEP_VERSION}/dep-linux-amd64
    - chmod +x /tmp/dep
    - export PATH=$PATH:/tmp/

install:
    - dep ensure -v

script: make coverage
